### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by yzaouga** [ekino/EkinoWordpressBundle#101]
Hi, is that bundle is compatible with s3 ? 

I keep getting this error when activating the plugin in wordpress:

Fatal error: Class 'Symfony\Component\ClassLoader\ClassCollectionLoader' not found in /Applications/MAMP/htdocs/wordpress/symfony/app/bootstrap.php.cache on line 2622 

thank you

**Comment by iatanasov77** [comment]
In Wordpress index.php file change this row $loader = require_once __DIR__.'/symfony/var/bootstrap.php.cache' to:
$loader = require __DIR__.'/symfony/app/autoload.php';

**Comment by yzaouga** [comment]
Thanks but not working.

what about the plugin core.php ?
```
require_once sprintf('%s/app/bootstrap.php.cache', WP_SYMFONY_PATH);
```

**Comment by eko** [comment]
Hi @yzaouga, @iatanasov77,

Symfony3's `bootstrap.php.cache` file is generated under `var/` directory instead of `app/` into eager versions.

This bundle support Symfony3 actually on latest versions. Maybe you're not on the right composer version?

Please feel free to close this issue if it is not still relevant.

**Comment by xyNNN** [comment]
This bundle is not compatible with Symfony 3.x+ due the deprecation of the SecurityContext (see https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/SecurityContext.php). This class is required by the WordpressRequestListener

**Comment by xyNNN** [comment]
To provide compatibility with Symfony 3.x we could replace the deprecated SecurityContext with the security.token_storage
