### ISSUE TITLE
Login in Wordpress using Symfony credentials

### ISSUE THREAD

**Issue by vicmar** [ekino/EkinoWordpressBundle#108]
Not really an issue, just a question (I'm sorry if this is not the place to ask, in that case tell me how).

I've got a Symfony project up and running and now i want to add a Wordpress blog but i would like users to be able to comment on Wordpress blog using their Symfony username and password (FOSUserBundle). Is this possible with this bundle?

Thanks a lot.

**Comment by eko** [comment]
Hi @vicmar,

Sorry for the late answer.

Technically, yes, that's possible because you can retrieve the Symfony security context at any time into WordPress so you can override the WordPress's comment system in order to use the Symfony user information instead.

I can't help you more on this subject because I've not implemented that actually but do not hesitate to let us know if you have found a solution.

I'm closing this issue as this is not really an issue. Feel free to reopen.
