### ISSUE TITLE
Add description of "Why?"

### ISSUE THREAD

**Issue by pbowyer** [ekino/EkinoWordpressBundle#58]
This is a fascinating project, and I found it while researching integrating Symfony2 with another CMS (to get round the pain of building custom apps on the CMS's antiquated structures).

What the repository doesn't tell me is Why - why did you do this? What's your use-case that this integration satisfied? Where did it succeed and where did it fail? What are its limitations

I'm conscious that Symfony2 is heavy, so why it vs a Silex-like equivalent? [My reasoning would be "bundles, bundles, bundles", but I'd like to hear yours...]

If you can share any case studies/examples of how this bundle was deployed and what it let you achieve, that would really help me evaluate an integration with another CMS. Thanks!

**Comment by GromNaN** [comment]
Hi to bring my 2c: I use this bundle to share WP authentication with a Symfony app (Single Sign On).
That's all, I don't use the Doctrine Model to access WP database from Symfony.

**Comment by eko** [comment]
Hi @pbowyer,

Initially, this bundle was made in order to build business logic under Symfony instead of Wordpress which is not really powerful to build things like that and we prefer to use it for its CMS features.

We've tried to implement most use cases with this bundle: integrate Symfony into Wordpress and also integrate Wordpress into Symfony.
Some people want to interact with the Wordpress database into Symfony, others want to build custom business logic into Symfony and use it in Wordpress, there are a lot of use cases.

We haven't tried to couple Wordpress with Silex and the bundle structure of Symfony brings all of what we need to do that. So yes, Symfony is heavier than Silex but we have a single package which made it easy.

I will be pleased to let you trying to make a POC if you want to link Wordpress with Silex.

**Comment by eko** [comment]
Closing this issue as I think the question of "Why" has been answered.

**Comment by pbowyer** [comment]
Yes, answered very well thanks!
