### ISSUE TITLE
How To...

### ISSUE THREAD

**Issue by J-who** [ekino/EkinoWordpressBundle#75]
Hey, thanks for this bundle!

I've got it everything setup and working like a charm so far. I'm hoping you can point me in the right direction to get started with the next few steps.

1) I need to create a couple custom tools to use in the wp admin panel. I'd be fine with the wp-admin menu just having links to Symfony and displaying on the right side. But I'd need to use symfony forms..

2) I need to allow users to sign up on the website. (fosuserbundle) And then use a few other simple custom made tools. How would I implement symfony forms into frontend of wordpress? 

I hope I'm going about this in the right direction...

Thanks!

**Comment by eko** [comment]
Hi @J-who,

This is totally possible with the `EkinoWordpressBundle` coupled to the Wordpress `ekino-wordpress-symfony` plugin (see: https://github.com/ekino/ekino-wordpress-symfony).

This way you can retrieve your Doctrine entity managers with the following new function provided by Wordpress plugin:

```php
$manager = \symfony_service('your.entity.manager');
$data = $manager->findAll();
```

This way, you can access your data and use them into a custom Wordpress admin panel.

About your question on using Symfony forms into Wordpress, there is no problem too as you are able to call the Symfony Form component builder and create your Symfony forms.

However, I suggest you to create a custom Symfony page for that in order to keep the Symfony things into Symfony.

Hope it helps.

**Comment by eko** [comment]
Closing as there is no real issue here.
