### ISSUE TITLE
symfony assest configuration, how acces

### ISSUE THREAD

**Issue by grekpg** [ekino/EkinoWordpressBundle#77]
Hi please see here http://stackoverflow.com/questions/29588330/ekinowordpressbundle-assest-path-configuration

**Comment by eko** [comment]
Hi @grekpg,

I just take a look at your question on Stackoverflow. I see at least 2 ways to solve this problem.

### 1 - Create symlinks on your assets directories

The simple way will be to add symlinks on your (Wordpress) root directory to the `symfony/web/js` and `symfony/web/bundles` for instance:

```bash
$ ln -s symfony/web/js js
$ ln -s symfony/web/bundles bundles
```

### 2 - Override the Symfony assets UrlPackage class

You can override the base url used by the Symfony assets management by overriding the `Symfony\Component\Templating\Asset\UrlPackage` class.

Create a new custom class:

```php
<?php

namespace Acme\DemoBundle\Templating\Asset;

use Symfony\Component\Templating\Asset\UrlPackage as BaseUrlPackage;

/**
 * UrlPackage
 */
class UrlPackage extends BaseUrlPackage
{
    /**
     * {@inheritdoc}
     */
    public function getBaseUrl($path)
    {
        $baseUrl = parent::getBaseUrl($path);

        return sprintf('/symfony/%s', $baseUrl);
    }
}

```
and then define the new class into the appropriate parameter in your `config.yml` file:

```yml
parameters:
    templating.asset.url_package.class: Acme\DemoBundle\Templating\Asset\UrlPackage
```

Maybe we could add this `UrlPackage` class into the bundle. Do you feel ok to submit us a pull request to integrate it with a new bundle configuration entry?

Otherwise, I will try to implement it as soon as possible.

Hope it helps.

Thank you for your feedback.

**Comment by grekpg** [comment]
thanks, now assest work fine - i use symlink version.
