### ISSUE TITLE
method symfony()

### ISSUE THREAD

**Issue by dacosta-rafael** [ekino/EkinoWordpressBundle#82]
How do I resolve for " Call to undefined function symfony()  "

**Comment by GromNaN** [comment]
You must install the [ekino-wordpress-symfony](https://github.com/ekino/ekino-wordpress-symfony).

**Comment by dacosta-rafael** [comment]
Hi GromNaN, I did but still at issue.

**Comment by eko** [comment]
Hi @dacosta-rafael,

You have to update your `index.php` file in order to define the `symfony()` function, as described here in this README part: https://github.com/ekino/EkinoWordpressBundle#4-update-your-wordpress-indexphp-file-to-load-symfony-libraries

Hope it helps, there is nothing else to do.

Please, do not hesitate to close this issue when resolved.

Thank you
